---
- hosts: s3-sync-server
  tasks:
  - debug:
      msg: "This is an Ansible playbook"

#  - name: copy cron job config
#    template:
#      src: "etc_crond_s3-sync-cron.j2"
#      dest: "/etc/cron.d/s3-sync-cron"
#      owner: root
#      group: root
#      mode: 0755

  - name: create folder for script
    file:
      path: "/opt/aidoc/"
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755
    become: True

  - name: copy cron job config
    template:
      src: "opt_aidoc_s3-sync.sh.j2"
      dest: "/opt/aidoc/s3-sync.sh.j2"
      owner: vagrant
      group: vagrant
      mode: 0755